weather:
  aag_cloud:
    serial_port: /dev/ttyUSB0
    threshold_cloudy: -25
    threshold_very_cloudy: -15
    threshold_windy: 50
    threshold_very_windy: 75
    threshold_gusty: 100
    threshold_very_gusty: 125
    threshold_wet: 2200
    threshold_rainy: 1800
    safety_delay: 15
    ignore_unsafe: null # null for None, otherwise can be a list, e.g. 'rain','cloud','gust','wind'
    heater:
      low_temp: 0
      low_delta: 6
      high_temp: 20
      high_delta: 4
      min_power: 10
      impulse_temp: 10
      impulse_duration: 60
      impulse_cycle: 600
  plot:
    amb_temp_limits:
      - -5
      - 40
    cloudiness_limits:
      - -45
      - 5
    wind_limits:
      - 0
      - 75
    rain_limits:
      - 700
      - 3200
    pwm_limits:
      - -5
      - 105
location:
  name: AAG Weather Station
  elevation: 1000.0  # meters
  latitude: 19.54  # degrees
  longitude: -155.58  # degrees
  timezone: US/Hawaii
